setup basics componets, pages and structure
eydenVi/2022React-Bootcamp-CapstoneProject pull request #1
Opened 2022-06-06 00:41 UTC by eydenVi

2022-06-07 16:08 UTC, buty619 requested changes

2022-06-07 16:08 UTC, buty619 commented on package.json
> +    "react-icons": "^4.4.0",
i don't think is a good idea install, this huge library just to use some few icons i prefer if you use it as svg react component or as image whit css.

2022-06-07 16:08 UTC, buty619 commented on src/components/categories/Categories.jsx
> +const Styles = styled.div`
please check the identation of all files, please always handle 2 spaces identation.

2022-06-07 16:08 UTC, buty619 commented on src/components/categories/Categories.jsx
> +	const {categories} = props;
you can destructor this on the input props of the arrow function, ej `const Categories = ({categories}) => {`

2022-06-07 16:08 UTC, buty619 commented on src/components/categories/Categories.jsx
> +	const renderCategories = () => {
i think we is better to make the `categories.map(..)` on the JSX and avoid indirections.

2022-06-07 16:08 UTC, buty619 commented on src/components/categories/Category.jsx
> +	const {properties} = props;
same comment as above

2022-06-07 16:08 UTC, buty619 commented on src/components/categories/Category.jsx
> +	const renderCategoryCard = () => {
same comment as above, please avoid indirections.

2022-06-07 16:08 UTC, buty619 commented on src/components/header/SearchField.jsx
> +	const { changeSearchField } = props;
same comment as above

2022-06-07 16:08 UTC, buty619 commented on src/components/products/Product.jsx
> +	const { properties } = props;
same comment as above

2022-06-07 16:08 UTC, buty619 commented on src/components/products/Product.jsx
> +	const renderProductCard = () => {
same comment as above

2022-06-07 16:08 UTC, buty619 commented on src/components/slider/Slider.jsx
> +	const nextSlide = () => {
i think this could be his own component

2022-06-07 16:08 UTC, buty619 commented on src/components/slider/Slider.jsx
> +	const prevSlide = () => {
i think this could be his own component

2022-06-10 19:41 UTC, eydenVi commented on package.json
> +    "react-icons": "^4.4.0",
Done

2022-06-10 20:30 UTC, buty619 requested changes

2022-06-10 20:30 UTC, buty619 commented on src/components/slider/Slider.jsx
> +  const renderSlides = () => {
como te comentaba esta indireccion creo que no es conveniente, por fa corrígela ¡

2022-06-10 20:30 UTC, buty619 commented on src/pages/Content.jsx
> +const Content = props => {
te falto arreglar la identación de este file

2022-06-10 20:30 UTC, buty619 commented on src/pages/Footer.jsx
> +		<div>
te falto arreglar la identación de este file

2022-06-10 20:30 UTC, buty619 commented on src/pages/Home.jsx
> +		<>
te falto arreglar la identación de este file

2022-06-10 20:30 UTC, buty619 commented on src/pages/Layout.jsx
> +		<div className="App">
te falto arreglar la identación de este file

2022-06-10 20:30 UTC, buty619 commented on src/utils/constants.js
> +const size = {
te falto arreglar la identación de este file

2022-06-10 20:30 UTC, buty619 commented on src/utils/truncate.js
> +	(toTruncate.length > maxLength ? `${toTruncate.substring(0, maxLength)}...` : toTruncate);
te falto arreglar la identación de este file

2022-06-10 21:22 UTC, buty619 approved these changes
🤟 excelente trabajo ¡¡ gracias por todas las modificaciones ¡¡

2022-06-11 00:06 UTC, merged